Bump HerdDB from 0.15.2 to 0.21.0
diennea/carapaceproxy pull request #226
Opened 2020-11-19 07:54 UTC by pv3nturi

2020-11-19 09:25 UTC, eolivelli requested changes
we are close to the release of HerdDB 0.22.0
I suggest you to wait

2020-11-19 09:25 UTC, eolivelli requested changes

2020-11-19 09:25 UTC, eolivelli commented on carapace-server/pom.xml
> +            <version>4.12.0</version>
btw this is not the version of BK that is in HerdDB 0.21.0

2020-12-01 08:11 UTC, aluccaroni approved these changes

2020-12-01 08:12 UTC, aluccaroni requested changes
@pv3nturi can you ensure that the version of BK is the same officially supported in herddb 0.22?

2020-12-01 08:17 UTC, pv3nturi commented
> @pv3nturi can you ensure that the version of BK is the same officially supported in herddb 0.22?
I'll fix it in next commit

2021-02-23 14:36 UTC, closed without merging