Accesslog rotation
diennea/carapaceproxy pull request #233
Opened 2020-12-07 23:18 UTC by hamadodene

2020-12-08 18:48 UTC, eolivelli requested changes

2020-12-08 18:48 UTC, eolivelli commented on carapace-server/src/main/java/org/carapaceproxy/server/RequestsLogger.java
> +                LOG.info("Maximum access log size reached.");
please log the filename, the size and the max size

2020-12-08 18:48 UTC, eolivelli commented on carapace-server/src/main/java/org/carapaceproxy/server/RequestsLogger.java
> +                File newAccessLogPath = new File(accesslogPath + "-" + System.currentTimeMillis());
why System.currentTimeMills ? it may be ugly

2020-12-08 18:48 UTC, eolivelli commented on carapace-server/src/main/java/org/carapaceproxy/server/RequestsLogger.java
> +                file.renameTo(newAccessLogPath);
you should use the java.io.Path API (new Java IO API, introduced in Java 7 ! )
there are utilities in Files that support "rename" with ATOMIC_MOVE flag

2021-02-15 16:45 UTC, pv3nturi requested changes

2021-02-15 16:45 UTC, pv3nturi commented on carapace-server/src/main/java/org/carapaceproxy/server/RequestsLogger.java
> +        FileChannel LogFileChannel = FileChannel.open(currentAccessLogPath);
camelCase

2021-02-15 16:45 UTC, pv3nturi commented on carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
> +        this.accessLogMaxSize =  properties.getLong("accessLog.maxSize", accessLogMaxSize);
properties always lowercase

2021-02-15 16:45 UTC, pv3nturi commented on carapace-server/src/main/java/org/carapaceproxy/server/RuntimeServerConfiguration.java
> +        LOG.info("accessLog.maxSize=" + accessLogMaxSize);
properties always lowercase

2021-02-15 16:45 UTC, pv3nturi commented on carapace-server/src/test/java/org/carapaceproxy/server/RequestsLoggerTest.java
> +            FileChannel LogFileChannel = FileChannel.open(currentAccessLogPath);
camelCase

2021-02-15 16:45 UTC, pv3nturi commented on carapace-server/src/test/java/org/carapaceproxy/server/RequestsLoggerTest.java
> +            assertEquals(f.length,1);
Maybe we should check that logs properly works even after a rotation has been performed

2021-02-15 16:45 UTC, pv3nturi commented on carapace-server/src/test/java/org/carapaceproxy/server/RequestsLoggerTest.java
> +        try ( HttpProxyServer server = HttpProxyServer.buildForTests("localhost", 0, mapper, tmpDir.newFolder());) {
This is a bad formatting issue... Please fix editor formatting properties or disable/avoid auto-formatting

2021-02-22 16:24 UTC, merged