Certiticates > Add "Expiring Date" in static and manual certificates UI
diennea/carapaceproxy pull request #257
Opened 2021-02-22 12:16 UTC by pv3nturi

PR for #196

2021-02-22 12:56 UTC, hamadodene approved these changes
LGTM

2021-02-22 13:55 UTC, pv3nturi commented
I gonna add these improvements https://github.com/diennea/carapaceproxy/issues/193 here

2021-02-23 06:42 UTC, nicoloboschi requested changes
Looks good, we need to change an import in a test file IMHO

2021-02-23 06:42 UTC, nicoloboschi commented on carapace-server/src/test/java/org/carapaceproxy/api/StartAPIServerTest.java
> +import org.apache.curator.shaded.com.google.common.io.Files;
Did you mean java.nio.file.Files?

2021-02-23 08:30 UTC, nicoloboschi approved these changes
+1

2021-02-23 09:38 UTC, merged