In-memory certificates data improvement
diennea/carapaceproxy pull request #282
Opened 2021-05-05 13:36 UTC by pv3nturi

Improved certificates data management on memory:

- serial number, expiring date and keystore data are now keep in memory and not more retrived from decoded chain

2021-05-05 13:41 UTC, pv3nturi commented on carapace-server/src/main/java/org/carapaceproxy/server/certificates/DynamicCertificatesManager.java
> -                CertificateData cert = loadOrCreateDynamicCertificateForDomain(domain, data.isWildcard(), false, data.getDaysBeforeRenewal());
We skip retriving the certificate from db which is already up-to-date. (all certs are reloaded as soon as a node triggers fire-cache request)

2021-05-05 13:42 UTC, pv3nturi commented on carapace-server/src/main/java/org/carapaceproxy/utils/CertificatesUtils.java
> -            ((X509Certificate) chain[0]).checkValidity(cal.getTime());
This checks notBefore and notAfter. Maybe we just need notAfter.

2021-05-11 11:25 UTC, nicoloboschi requested changes
It looks good, I left a comment on the expire date check

2021-05-12 08:57 UTC, nicoloboschi approved these changes
+1

2021-05-12 11:51 UTC, merged