Reactor netty migration
diennea/carapaceproxy pull request #303
Opened 2021-09-14 14:40 UTC by pv3nturi

Migrating the connections core management to Reactor Netty

2021-09-20 08:13 UTC, diegosalvi requested changes

2021-09-20 08:13 UTC, diegosalvi commented on carapace-server/src/main/java/org/carapaceproxy/core/ProxyRequestsManager.java
> +    public ConcurrentHashMap<EndpointKey, EndpointStats> getEndpointsStats() {
I wouldn't expose externally the map implementation, can it even be modified externally?

2021-12-01 14:32 UTC, diegosalvi approved these changes

2021-12-01 16:56 UTC, dmercuriali approved these changes

2021-12-01 16:56 UTC, merged