Fix yarn Dependabot alerts
diennea/carapaceproxy pull request #339
Opened 2022-03-28 11:16 UTC by hamadodene

2022-03-28 12:59 UTC, nicoloboschi requested changes

2022-03-28 13:10 UTC, hamadodene commented on carapace-ui/src/main/webapp/package.json
> +    "vue": "3.2.31",
Yes, you are right

2022-03-28 16:08 UTC, hamadodene commented
PTAL @nicoloboschi

2022-03-29 19:57 UTC, nicoloboschi approved these changes

2022-03-30 08:31 UTC, pv3nturi approved these changes

2022-03-30 08:31 UTC, merged