Return Service unavailable when all backend is down
diennea/carapaceproxy pull request #466
Opened 2024-03-28 08:28 UTC by hamadodene

#436

2024-03-28 09:01 UTC, NiccoMlt requested changes
Looks good to me, but you need to fix a couple of tests:

- org.carapaceproxy.backends.StuckRequestsTest ► testBackendUnreachableOnStuckRequest(true)
- org.carapaceproxy.server.mapper.BasicStandardEndpointMapperTest ► testRouteErrors

2024-03-28 10:26 UTC, hamadodene commented
@NiccoMlt test Fixed

2024-03-28 10:26 UTC, NiccoMlt requested changes
Good job! Just a nitpick and we can go

2024-03-28 10:26 UTC, NiccoMlt commented on carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java
>          return super.mapServiceUnavailableError(routeId);
We can leverage the `Optional` better here, i.e. like it follows:

```java
// custom for route
Optional<RouteConfiguration> config = routes.stream().filter(r -> r.getId().equalsIgnoreCase(routeid)).findFirst();
ActionConfiguration errorAction = config
        .map(RouteConfiguration::getErrorAction)
        .map(actions::get)
        // custom global
        .orElseGet(() -> defaultInternalErrorAction != null ? actions.get(defaultInternalErrorAction) : null);
if (errorAction != null) {
    return new SimpleHTTPResponse(errorAction.getErrorCode(), errorAction.getFile(), errorAction.getCustomHeaders());
}
// fallback
return super.mapInternalError(routeid);
```

2024-03-28 10:26 UTC, NiccoMlt commented on carapace-server/src/main/java/org/carapaceproxy/server/mapper/StandardEndpointMapper.java
> +        }
This part is pretty much identical in:

- `mapInternalError`: lines 258-273
- `mapServiceUnavailableError`: lines 280-295

Maybe we should group it in an external method?

2024-05-11 17:13 UTC, NiccoMlt approved these changes
Good job!

2024-05-11 17:15 UTC, merged