feat(server): implement CRUD APIs for connection pool
diennea/carapaceproxy pull request #473
Opened 2024-05-06 15:54 UTC by NiccoMlt

2024-05-21 19:13 UTC, hamadodene requested changes
Ok to me… I’ve seen that you made many changes. Some of them don’t seem related to the attached issue. Can you provide a brief description of what you’ve done? 
@pv3nturi  @dmercuriali can you also take a look?

2024-05-22 16:13 UTC, NiccoMlt commented
> Ok to me… I’ve seen that you made many changes. Some of them don’t seem related to the attached issue. Can you provide a brief description of what you’ve done? @pv3nturi @dmercuriali can you also take a look?

@hamadodene you're right, I added to the description those additional fixes.

They're mostly tiny and non-invasive, but they were pretty much needed.

If you want @pv3nturi or @dmercuriali to take a look, please mark them as reviewers in this PR to keep track of it

2024-05-23 07:32 UTC, dmercuriali approved these changes

2024-05-23 07:51 UTC, hamadodene approved these changes

2024-05-23 07:51 UTC, merged